# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ting's Git Blog
email: doesnotexist@tinglik
description: > # this means to ignore newlines until "baseurl:"
  Still debating what to write here in my _config.yml. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.tinglik.to" # the base hostname & protocol for your site
twitter_username: mrtingalingling
github_username:  mrtingalingling

# Build settings
markdown: kramdown

theme: jekyll-theme-midnight
